server {
  listen 80;
  server_name anyobjects.ru www.anyobjects.ru;

  root /home/YOUR_USER/anyobjects.ru;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ^~ /api/ {
    try_files $uri =404;
  }

  location ^~ /uploads/ {
    try_files $uri =404;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|otf|webmanifest)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }

  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
  }
}
